plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrx7014.1ui8spoofer'
    compileSdk 34

    defaultConfig {
        applicationId "com.mrx7014.1ui8spoofer"
        minSdk 29
        targetSdk 34
        versionCode 100
        versionName "1.0.0"
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    compileOnly 'de.robv.android.xposed:api:82'
}
